/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzarendeles;

import javax.swing.JOptionPane;

/**
 *
 * @author PalkovicsAlex(SZOFT_
 */
public class Pizzarendeles extends javax.swing.JFrame {

    /**
     * Creates new form Pizzarendeles
     */
    public Pizzarendeles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tesztaFele = new javax.swing.ButtonGroup();
        szoszFele = new javax.swing.ButtonGroup();
        lblPizzarend = new javax.swing.JLabel();
        lblTeszta = new javax.swing.JLabel();
        panelTeszta = new javax.swing.JPanel();
        rabVekony = new javax.swing.JRadioButton();
        rabNapolyi = new javax.swing.JRadioButton();
        rabVastag = new javax.swing.JRadioButton();
        lblSzosz = new javax.swing.JLabel();
        panelSzosz = new javax.swing.JPanel();
        rabParSzosz = new javax.swing.JRadioButton();
        rabSajtszosz = new javax.swing.JRadioButton();
        rabTejfol = new javax.swing.JRadioButton();
        lblFeltet = new javax.swing.JLabel();
        btnKuldes = new javax.swing.JButton();
        lblEgyeb = new javax.swing.JLabel();
        txtEgyeb = new javax.swing.JTextField();
        cbxAfa = new javax.swing.JCheckBox();
        lblRendelo = new javax.swing.JLabel();
        txtRendelo = new javax.swing.JTextField();
        panelFeltet = new javax.swing.JPanel();
        cbxMozza = new javax.swing.JCheckBox();
        cbxTonhal = new javax.swing.JCheckBox();
        cbxJalapeno = new javax.swing.JCheckBox();
        cbxSonka = new javax.swing.JCheckBox();
        cbxParadicsom = new javax.swing.JCheckBox();
        cbxCsirke = new javax.swing.JCheckBox();
        cbxOliva = new javax.swing.JCheckBox();
        cbxSzalami = new javax.swing.JCheckBox();
        cbxGomba = new javax.swing.JCheckBox();
        cbxKukorica = new javax.swing.JCheckBox();
        cbxAnanasz = new javax.swing.JCheckBox();
        cbxBazsa = new javax.swing.JCheckBox();
        panelEgyeb = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbxMeret = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        spinMennyiseg = new javax.swing.JSpinner();
        comFajta = new javax.swing.JComboBox<>();
        lblFajta = new javax.swing.JLabel();
        panelKep = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizza feladása");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        lblPizzarend.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPizzarend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPizzarend.setText("Pizzarendelés");

        lblTeszta.setText("Tészta");

        panelTeszta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tesztaFele.add(rabVekony);
        rabVekony.setText("Vékony");

        tesztaFele.add(rabNapolyi);
        rabNapolyi.setText("Nápolyi");

        tesztaFele.add(rabVastag);
        rabVastag.setText("Vastag");

        javax.swing.GroupLayout panelTesztaLayout = new javax.swing.GroupLayout(panelTeszta);
        panelTeszta.setLayout(panelTesztaLayout);
        panelTesztaLayout.setHorizontalGroup(
            panelTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTesztaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rabVekony, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rabNapolyi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rabVastag, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelTesztaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rabNapolyi, rabVastag, rabVekony});

        panelTesztaLayout.setVerticalGroup(
            panelTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTesztaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rabVekony)
                    .addComponent(rabNapolyi)
                    .addComponent(rabVastag))
                .addContainerGap())
        );

        lblSzosz.setText("Szósz");

        panelSzosz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        szoszFele.add(rabParSzosz);
        rabParSzosz.setText("Paradicsom");

        szoszFele.add(rabSajtszosz);
        rabSajtszosz.setText("Sajtszósz");
        rabSajtszosz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabSajtszoszActionPerformed(evt);
            }
        });

        szoszFele.add(rabTejfol);
        rabTejfol.setText("Tejföl");

        javax.swing.GroupLayout panelSzoszLayout = new javax.swing.GroupLayout(panelSzosz);
        panelSzosz.setLayout(panelSzoszLayout);
        panelSzoszLayout.setHorizontalGroup(
            panelSzoszLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSzoszLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rabParSzosz, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(rabSajtszosz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rabTejfol, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panelSzoszLayout.setVerticalGroup(
            panelSzoszLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSzoszLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSzoszLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rabParSzosz)
                    .addComponent(rabSajtszosz)
                    .addComponent(rabTejfol))
                .addContainerGap())
        );

        lblFeltet.setText("Feltét");

        btnKuldes.setBackground(new java.awt.Color(255, 204, 102));
        btnKuldes.setText("Küldés");
        btnKuldes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKuldesActionPerformed(evt);
            }
        });

        lblEgyeb.setText("Egyebek");

        cbxAfa.setText("ÁFÁ-s számla");

        lblRendelo.setText("Rendelő:");

        panelFeltet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cbxMozza.setText("Mozzarella");

        cbxTonhal.setText("Tonhal");

        cbxJalapeno.setText("Jalapeno");

        cbxSonka.setText("Sonka");

        cbxParadicsom.setText("Paradicsom");

        cbxCsirke.setText("Csirke");

        cbxOliva.setText("Olivabogyó");

        cbxSzalami.setText("Szalámi");

        cbxGomba.setText("Gomba");

        cbxKukorica.setText("Kukorica");

        cbxAnanasz.setText("Ananász");

        cbxBazsa.setText("Bazsalikom");

        javax.swing.GroupLayout panelFeltetLayout = new javax.swing.GroupLayout(panelFeltet);
        panelFeltet.setLayout(panelFeltetLayout);
        panelFeltetLayout.setHorizontalGroup(
            panelFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFeltetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxParadicsom)
                    .addComponent(cbxKukorica)
                    .addComponent(cbxGomba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxOliva)
                    .addComponent(cbxJalapeno)
                    .addComponent(cbxTonhal))
                .addGap(18, 18, 18)
                .addGroup(panelFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxCsirke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxSzalami, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxSonka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxMozza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxBazsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxAnanasz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelFeltetLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxGomba, cbxKukorica, cbxParadicsom});

        panelFeltetLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxJalapeno, cbxOliva, cbxTonhal});

        panelFeltetLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxCsirke, cbxSzalami});

        panelFeltetLayout.setVerticalGroup(
            panelFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFeltetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelFeltetLayout.createSequentialGroup()
                            .addComponent(cbxMozza)
                            .addGap(18, 18, 18)
                            .addComponent(cbxBazsa)
                            .addGap(18, 18, 18)
                            .addComponent(cbxAnanasz))
                        .addGroup(panelFeltetLayout.createSequentialGroup()
                            .addComponent(cbxSonka)
                            .addGap(18, 18, 18)
                            .addComponent(cbxCsirke)
                            .addGap(18, 18, 18)
                            .addComponent(cbxSzalami)))
                    .addGroup(panelFeltetLayout.createSequentialGroup()
                        .addComponent(cbxParadicsom)
                        .addGap(18, 18, 18)
                        .addComponent(cbxKukorica)
                        .addGap(18, 18, 18)
                        .addComponent(cbxGomba))
                    .addGroup(panelFeltetLayout.createSequentialGroup()
                        .addComponent(cbxOliva)
                        .addGap(18, 18, 18)
                        .addComponent(cbxJalapeno)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTonhal)))
                .addGap(44, 44, 44))
        );

        jLabel8.setText("Méret");

        cbxMeret.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "24 cm", "32 cm", "50 cm" }));

        jLabel7.setText("Mennyiség");

        spinMennyiseg.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spinMennyiseg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panelEgyebLayout = new javax.swing.GroupLayout(panelEgyeb);
        panelEgyeb.setLayout(panelEgyebLayout);
        panelEgyebLayout.setHorizontalGroup(
            panelEgyebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEgyebLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEgyebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(panelEgyebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinMennyiseg)
                    .addComponent(cbxMeret, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEgyebLayout.setVerticalGroup(
            panelEgyebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEgyebLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEgyebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spinMennyiseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEgyebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        comFajta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Válasszon Pizzát! (beta)", "Margherita", "Mediterrán", "Négy Évszak" }));
        comFajta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comFajtaItemStateChanged(evt);
            }
        });

        lblFajta.setText("Pizza:");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/pizza.png"))); // NOI18N

        javax.swing.GroupLayout panelKepLayout = new javax.swing.GroupLayout(panelKep);
        panelKep.setLayout(panelKepLayout);
        panelKepLayout.setHorizontalGroup(
            panelKepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKepLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelKepLayout.setVerticalGroup(
            panelKepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelKep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRendelo)
                                    .addComponent(lblFajta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comFajta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRendelo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(lblSzosz))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(lblFeltet))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtEgyeb)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(panelEgyeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6))
                                .addComponent(panelSzosz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(180, 180, 180)
                                    .addComponent(lblEgyeb))
                                .addComponent(panelFeltet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelTeszta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(cbxAfa)
                                .addGap(50, 50, 50)
                                .addComponent(btnKuldes)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblPizzarend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTeszta)
                .addGap(183, 183, 183))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblFajta, lblRendelo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comFajta, txtRendelo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPizzarend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRendelo)
                            .addComponent(txtRendelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comFajta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFajta))))
                .addGap(18, 18, 18)
                .addComponent(lblTeszta)
                .addGap(12, 12, 12)
                .addComponent(panelTeszta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSzosz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSzosz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblFeltet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFeltet, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEgyeb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEgyeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEgyeb))
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKuldes)
                    .addComponent(cbxAfa))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rabSajtszoszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabSajtszoszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rabSajtszoszActionPerformed

    private void btnKuldesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKuldesActionPerformed
        boolean rendeloNev = "".equals(txtRendelo.getText());
        int mennyiseg = (int) spinMennyiseg.getValue();
        String uzenet, cim = "FIGYELEM!";
        int ikonTipus;
        if(rendeloNev){
            cim = cim + " - Nincs név";
            uzenet = "Nincsen beírva a rendelőnek a neve!";
            ikonTipus = JOptionPane.WARNING_MESSAGE;
        }else if(mennyiseg == 0){
            cim = cim + " - Nincs mennyiség";
            uzenet = "Nincsen megadva, hogy mennyi pizza legyen megrendelve!";
            ikonTipus = JOptionPane.WARNING_MESSAGE;
        }
        else{
            cim = "Sikeres rendelés!";
            uzenet = "Sikeresen feladta a rendelést!";
            ikonTipus = JOptionPane.INFORMATION_MESSAGE;
        }
        JOptionPane.showMessageDialog(null, uzenet, cim, ikonTipus);
//        String cim;
//        String uzenet;
//        cim = "Sikeres rendelés";
//        uzenet = "Sikeresen feladta a rendelést!";
//        JOptionPane.showMessageDialog(rootPane, uzenet, cim, 1);
//        System.exit(0);
    }//GEN-LAST:event_btnKuldesActionPerformed

    private void comFajtaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comFajtaItemStateChanged
        int pizzaFajta = comFajta.getSelectedIndex();
        switch (pizzaFajta) {
            case 1 -> {
                cbxMozza.setSelected(true);
                cbxTonhal.setSelected(false);
                cbxJalapeno.setSelected(false);
                cbxSonka.setSelected(false);
                cbxParadicsom.setSelected(true);
                cbxCsirke.setSelected(false);
                cbxOliva.setSelected(false);
                cbxSzalami.setSelected(false);
                cbxGomba.setSelected(false);
                cbxKukorica.setSelected(false);
                cbxAnanasz.setSelected(false);
                cbxBazsa.setSelected(false);
            }
            case 2 -> {
                cbxMozza.setSelected(true);
                cbxTonhal.setSelected(false);
                cbxJalapeno.setSelected(false);
                cbxSonka.setSelected(false);
                cbxParadicsom.setSelected(false);
                cbxCsirke.setSelected(true);
                cbxOliva.setSelected(true);
                cbxSzalami.setSelected(false);
                cbxGomba.setSelected(false);
                cbxKukorica.setSelected(false);
                cbxAnanasz.setSelected(false);
                cbxBazsa.setSelected(false);
            }
            case 3 -> {
                cbxMozza.setSelected(true);
                cbxTonhal.setSelected(false);
                cbxJalapeno.setSelected(false);
                cbxSonka.setSelected(true);
                cbxParadicsom.setSelected(false);
                cbxCsirke.setSelected(false);
                cbxOliva.setSelected(false);
                cbxSzalami.setSelected(true);
                cbxGomba.setSelected(true);
                cbxKukorica.setSelected(true);
                cbxAnanasz.setSelected(false);
                cbxBazsa.setSelected(false);
            }
            default -> {
                cbxMozza.setSelected(false);
                cbxTonhal.setSelected(false);
                cbxJalapeno.setSelected(false);
                cbxSonka.setSelected(false);
                cbxParadicsom.setSelected(false);
                cbxCsirke.setSelected(false);
                cbxOliva.setSelected(false);
                cbxSzalami.setSelected(false);
                cbxGomba.setSelected(false);
                cbxKukorica.setSelected(false);
                cbxAnanasz.setSelected(false);
                cbxBazsa.setSelected(false);
            }
        }
    }//GEN-LAST:event_comFajtaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzarendeles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKuldes;
    private javax.swing.JCheckBox cbxAfa;
    private javax.swing.JCheckBox cbxAnanasz;
    private javax.swing.JCheckBox cbxBazsa;
    private javax.swing.JCheckBox cbxCsirke;
    private javax.swing.JCheckBox cbxGomba;
    private javax.swing.JCheckBox cbxJalapeno;
    private javax.swing.JCheckBox cbxKukorica;
    private javax.swing.JComboBox<String> cbxMeret;
    private javax.swing.JCheckBox cbxMozza;
    private javax.swing.JCheckBox cbxOliva;
    private javax.swing.JCheckBox cbxParadicsom;
    private javax.swing.JCheckBox cbxSonka;
    private javax.swing.JCheckBox cbxSzalami;
    private javax.swing.JCheckBox cbxTonhal;
    private javax.swing.JComboBox<String> comFajta;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblEgyeb;
    private javax.swing.JLabel lblFajta;
    private javax.swing.JLabel lblFeltet;
    private javax.swing.JLabel lblPizzarend;
    private javax.swing.JLabel lblRendelo;
    private javax.swing.JLabel lblSzosz;
    private javax.swing.JLabel lblTeszta;
    private javax.swing.JPanel panelEgyeb;
    private javax.swing.JPanel panelFeltet;
    private javax.swing.JPanel panelKep;
    private javax.swing.JPanel panelSzosz;
    private javax.swing.JPanel panelTeszta;
    private javax.swing.JRadioButton rabNapolyi;
    private javax.swing.JRadioButton rabParSzosz;
    private javax.swing.JRadioButton rabSajtszosz;
    private javax.swing.JRadioButton rabTejfol;
    private javax.swing.JRadioButton rabVastag;
    private javax.swing.JRadioButton rabVekony;
    private javax.swing.JSpinner spinMennyiseg;
    private javax.swing.ButtonGroup szoszFele;
    private javax.swing.ButtonGroup tesztaFele;
    private javax.swing.JTextField txtEgyeb;
    private javax.swing.JTextField txtRendelo;
    // End of variables declaration//GEN-END:variables

    private boolean equals(String rendeloNev, String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
